spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #远程服务器环境
#      url: jdbc:mysql://8.137.53.253:3306/corpusrole?characterEncoding=utf8&serverTimezone=GMT%2b8
#      username: corpusrole
#      password: CbHdmG7xF8fEyjs4
#  本地环境
      url: jdbc:mysql://localhost:3306/corpusrole
      username: root
      password: 123456
  servlet:
    multipart: #对上传的文件大小进行设置
      max-file-size: 20MB
      max-request-size: 100MB
#到时候可以根据实际情况更改端口号
server:
  port: 8080
#  servlet:
#    context-path: /api
logging:
  file:
    name: server.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      file-name-pattern: server.%d.%i.log
#存放密钥信息
api:
  key: myself_123456
#存放百度密钥信息
baidu:
  BaiDuAPI_KEY: 1uoRnTwzQAD9Zh2dniw90HIH
  BaiDuSECRET_KEY: b1dn5GiMqRglAGyGia23dD1nbXVb1Pri
  WenXinAPI: 8D9nuuAzMpfXUCSfbHX3rIsH
  WenXinSecurity: mNrRXKGjE8vT6KphLEtXmKfCode5MwRT
#存放语料的url
strapi:
  #上线前只需要更改这里的strapi的url就可以将整改代码的url更改
  #  url: http://localhost:1337/
  url: http://8.137.53.253:1337/

  #这个可能需要更新
  AuthToken: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzAyNzA4NzI3LCJleHAiOjE3MDUzMDA3Mjd9.80OUAPcEXzS-5tCVaTgM51zOgUHSg6cKixOPLGwRcYw
  #上传的语料资源的地址
  #  strapiUploadUrl: http://localhost:1337/upload
  strapiUploadUrl: http://8.137.53.253:1337/upload
